services:
    dispatcher:
        class: nicofuma\webprofiler\phpbb\event\traceable_dispatcher
        arguments:
            - @dispatcher_real
            - @stopwatch
        calls:
            - [setProfiler, ["@profiler"]]
            - [addSubscriber, ["@profiler.listener"]]
            - [addSubscriber, ["@profiler.data_collector.request"]]

    dispatcher_real:
        class: phpbb\event\dispatcher
        arguments:
            - @service_container

    template:
        class: nicofuma\webprofiler\phpbb\template\timed
        arguments:
            - @template.real
            - @stopwatch

    template.real:
        class: phpbb\template\twig\twig
        arguments:
            - @path_helper
            - @config
            - @user
            - @template_context
            - @ext.manager

    dbal.conn:
        class: nicofuma\webprofiler\phpbb\db\timed
        arguments:
            - @service_container
            - @stopwatch

    stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
        public: false

    profiler.data_collector.event:
        class: Symfony\Component\HttpKernel\DataCollector\EventDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.data_collector.time:
        class: Symfony\Component\HttpKernel\DataCollector\TimeDataCollector
        tags:
            - { name: profiler.data_collector }
