imports:
    - { resource: event_dispatcher_stopwatch.yml }

parameters:
    debug.load_time: true
    profiler.storage.dsn: file:%core.root_path%cache/profiler/

services:
    controller.resolver:
        class: Symfony\Component\HttpKernel\Controller\TraceableControllerResolver
        arguments:
            - @controller.resolver_real
            - @stopwatch

    controller.resolver_real:
        class: phpbb\controller\resolver
        arguments:
            - @user
            - @service_container
            - %core.root_path%
            - @template
        public: false

    url_matcher:
        class: nicofuma\webprofiler\phpbb\routing\url_matcher
        arguments:
            - @symfony_request
            - @ext.manager
            - %core.root_path%
            - %core.php_ext%

    profiler:
        class: nicofuma\webprofiler\phpbb\profiler\profiler
        arguments:
            - @profiler.data_collector.collection
            - @profiler.storage

    profiler.data_collector.collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: profiler.data_collector }

    profiler.data_collector.config:
        class: Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector
        tags:
            - { name: profiler.data_collector }
    profiler.data_collector.memory:
        class: Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector
        tags:
            - { name: profiler.data_collector }

    profiler.data_collector.request:
        class: Symfony\Component\HttpKernel\DataCollector\RequestDataCollector
        tags:
            - { name: profiler.data_collector }
            - { name: kernel.event_subscriber }

    profiler.data_collector.router:
        class: Symfony\Component\HttpKernel\DataCollector\RouterDataCollector
        tags:
            - { name: profiler.data_collector }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    profiler.listener:
        class: nicofuma\webprofiler\phpbb\profiler\profiler_listener
        arguments:
            - @symfony_request
            - @dispatcher
            - @http_kernel
            - %core.root_path%
            - %core.php_ext%
            - @profiler

    profiler.storage:
        class: Symfony\Component\HttpKernel\Profiler\FileProfilerStorage
        arguments:
            - %profiler.storage.dsn%

    stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
        public: false
