nicofuma_webprofiler_profiler_home:
    path: _profiler/
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:homeAction }

nicofuma_webprofiler_profiler_search:
    path: _profiler/search
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:searchAction }

nicofuma_webprofiler_profiler_search_bar:
    path: _profiler/search_bar
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:searchBarAction }

nicofuma_webprofiler_profiler_purge:
    path: _profiler/purge
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:purgeAction }

nicofuma_webprofiler_profiler_info:
    path: _profiler/info/{about}
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:infoAction }

nicofuma_webprofiler_profiler_phpinfo:
    path: _profiler/phpinfo
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:phpinfoAction }

nicofuma_webprofiler_profiler_search_results:
    path: _profiler/{token}/search/results
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:searchResultsAction }

nicofuma_webprofiler_profiler:
    path: _profiler/{token}
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:panelAction }

nicofuma_webprofiler_profiler_router:
    path: _profiler/{token}/router
    defaults: { _controller: nicofuma.webprofiler.controller.router:panelAction }

nicofuma_webprofiler_profiler_panel:
    path: _profiler/{token}/{panel}
    defaults: { _controller: nicofuma.webprofiler.controller.profiler:panelAction }

nicofuma_webprofiler_profiler_exception:
    path: _profiler/{token}/exception
    defaults: { _controller: nicofuma.webprofiler.controller.exception:showAction }

nicofuma_webprofiler_profiler_exception_css:
    path: _profiler/{token}/exception.css
    defaults: { _controller: nicofuma.webprofiler.controller.exception:cssAction }

nicofuma_webprofiler_wdt:
    path: _wdt/{token}
    defaults:
        _controller: nicofuma.webprofiler.controller.profiler:toolbarAction
