imports:
    - { resource: data_collector/config.yml }
    - { resource: data_collector/request.yml }
    - { resource: data_collector/event.yml }
    - { resource: data_collector/ajax.yml }
    - { resource: data_collector/time.yml }
    - { resource: data_collector/router.yml }
    - { resource: data_collector/memory.yml }
    - { resource: data_collector/database.yml }

parameters:
    nicofuma.webprofiler.profiler.storage.dsn: file:%core.root_path%cache/profiler/
    nicofuma.webprofiler.excluded_ajax_paths: /_wdt

services:
    nicofuma.webprofiler.controller.profiler:
        class: nicofuma\webprofiler\controller\profiler
        arguments:
            - @template
            - @controller.helper
            - @?nicofuma.webprofiler.profiler

    nicofuma.webprofiler.controller.router:
        class: nicofuma\webprofiler\controller\router
        arguments:
            - @template
            - @controller.helper
            - @controller.provider
            - @nicofuma.webprofiler.url_matcher
            - @?nicofuma.webprofiler.profiler

    nicofuma.webprofiler.event.debug_toolbar_listener:
        class: nicofuma\webprofiler\event\debug_toolbar_listener
        arguments:
            - @template
            - @controller.helper
        tags:
            - { name: kernel.event_subscriber }

    nicofuma.webprofiler.profiler:
        class: nicofuma\webprofiler\phpbb\profiler\profiler
        arguments:
            - @nicofuma.webprofiler.profiler.data_collector.collection
            - @nicofuma.webprofiler.profiler.storage

    nicofuma.webprofiler.profiler.data_collector.collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: profiler.data_collector }

    nicofuma.webprofiler.profiler.listener:
        class: nicofuma\webprofiler\phpbb\profiler\profiler_listener
        arguments:
            - @symfony_request
            - @dispatcher
            - @http_kernel
            - %core.root_path%
            - %core.php_ext%
            - @nicofuma.webprofiler.profiler

    nicofuma.webprofiler.profiler.storage:
        class: Symfony\Component\HttpKernel\Profiler\FileProfilerStorage
        arguments:
            - %nicofuma.webprofiler.profiler.storage.dsn%
