services:
    nicofuma.webprofiler.profiler.data_collector.ajax:
        class: Symfony\Component\HttpKernel\DataCollector\AjaxDataCollector
        tags:
            -
                name: data_collector
                template: "@WebProfiler/Collector/ajax.html.twig"
                id: ajax
                priority: 315
