services:
    nicofuma.webprofiler.profiler.data_collector.event:
        class: Symfony\Component\HttpKernel\DataCollector\EventDataCollector
        arguments:
            - "@dispatcher"
        tags:
            -
                name: data_collector
                template: "@WebProfiler/Collector/events.html.twig"
                id: events
                priority: 290
