services:
    nicofuma.webprofiler.profiler.data_collector.memory:
        class: Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector
        tags:
            -
                name: data_collector
                template: "@WebProfiler/Collector/memory.html.twig"
                id: memory
                priority: 325
