services:
    nicofuma.webprofiler.controller.resolver:
        class: Symfony\Component\HttpKernel\Controller\TraceableControllerResolver
        decorates: controller.resolver
        public: false
        arguments:
            - "@nicofuma.webprofiler.controller.resolver.inner"
            - "@nicofuma.webprofiler.stopwatch"


    nicofuma.webprofiler.profiler.data_collector.router:
        class: Symfony\Component\HttpKernel\DataCollector\RouterDataCollector
        tags:
            -
                name: data_collector
                template: "@WebProfiler/Collector/router.html.twig"
                id: router
                priority: 285
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
