services:
    dbal.conn:
        class: nicofuma\webprofiler\phpbb\db\timed
        arguments:
            - "@service_container"
            - "@nicofuma.webprofiler.stopwatch"

    nicofuma.webprofiler.dispatcher:
        class: nicofuma\webprofiler\phpbb\event\traceable_dispatcher
        decorates: dispatcher
        public: false
        arguments:
            - "@nicofuma.webprofiler.dispatcher.inner"
            - "@nicofuma.webprofiler.stopwatch"

    nicofuma.webprofiler.template:
        class: nicofuma\webprofiler\phpbb\template\timed
        decorates: template
        public: false
        arguments:
            - "@nicofuma.webprofiler.template.inner"
            - "@nicofuma.webprofiler.stopwatch"


    nicofuma.webprofiler.profiler.data_collector.time:
        class: Symfony\Component\HttpKernel\DataCollector\TimeDataCollector
        arguments:
            - ~
            - "@nicofuma.webprofiler.stopwatch"
        tags:
            -
                name: data_collector
                template: "@WebProfiler/Collector/time.html.twig"
                id: time
                priority: 330

    nicofuma.webprofiler.stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
        public: false
