services:
    dbal.conn:
        class: nicofuma\webprofiler\phpbb\db\timed
        arguments:
            - @service_container
            - @nicofuma.webprofiler.stopwatch

    dispatcher:
        class: nicofuma\webprofiler\phpbb\event\traceable_dispatcher
        arguments:
            - @nicofuma.webprofiler.dispatcher_real
            - @nicofuma.webprofiler.stopwatch
        calls:
            - [setProfiler, ["@nicofuma.webprofiler.profiler"]]
            - [addSubscriber, ["@nicofuma.webprofiler.profiler.listener"]]
            - [addSubscriber, ["@nicofuma.webprofiler.profiler.data_collector.request"]]

    nicofuma.webprofiler.dispatcher_real:
        class: phpbb\event\dispatcher
        arguments:
            - @service_container

    template:
        class: nicofuma\webprofiler\phpbb\template\timed
        arguments:
            - @nicofuma.webprofiler.template.real
            - @nicofuma.webprofiler.stopwatch

    nicofuma.webprofiler.template.real:
        class: phpbb\template\twig\twig
        arguments:
            - @path_helper
            - @config
            - @user
            - @template_context
            - @template.twig.environment
            - %core.template.cache_path%
            - @template.twig.extensions.collection
            - @ext.manager

    nicofuma.webprofiler.profiler.data_collector.time:
        class: Symfony\Component\HttpKernel\DataCollector\TimeDataCollector
        tags:
            - { name: profiler.data_collector }

    nicofuma.webprofiler.stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
        public: false
