services:
    nicofuma.webprofiler.profiler.data_collector.twig:
        class: Symfony\Bridge\Twig\DataCollector\TwigDataCollector
        arguments:
            - "@nicofuma.webprofiler.twig.profile"
        tags:
            -
                name: data_collector
                template: "@WebProfiler/Collector/twig.html.twig"
                id: twig
                priority: 257

    nicofuma.webprofiler.twig.profile:
        class: Twig_Profiler_Profile

    nicofuma.webprofiler.twig.extension.profiler:
        class: Symfony\Bridge\Twig\Extension\ProfilerExtension
        arguments:
            - "@nicofuma.webprofiler.twig.profile"
            - "@?nicofuma.webprofiler.stopwatch"
        tags:
            - { name: twig.extension }
